spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.234.79.216:3306/blogs?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: blogs
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    root: info
    com.lrm: error
  file: log/blog.log



